/*
 * Copyright (c) 2018.  HobbitSoft - Kevin Heath High
 */

package net.hobbitsoft.popularmovies.constants;

import net.hobbitsoft.popularmovies.R;

/* Constants class for defining Type of Movie to return Popular or Top Rated"
The values are random and generated by the Android Studio IDE
*/
public class MenuType {

    public static final int POPULAR = R.id.lt_mn_popular;
    public static final int TOP_RATED = R.id.lt_mn_top_rated;
    public static final int FAVORITES = R.id.lt_mn_favorites;

    public static final int OVERVIEW = R.id.mi_menu_overview;
    public static final int TRAILERS = R.id.mi_menu_trailers;
    public static final int REVIEWS = R.id.mi_menu_reviews;

}
