/*
 * Copyright (c) 2018.  HobbitSoft - Kevin Heath High
 */

package net.hobbitsoft.popularmoviesstageone.constants;

/* Constants class for defining Type of Movie to return Popular or Top Rated"
The values are random and generated by the Android Studio IDE
*/
public class ListType {

    public static final int POPULAR = 918;
    public static final int TOP_RATED = 245;

}
